
						
						
						
						
						
						
						
						
						
						
						
						
						
						
						
						
						<li class="ui-state-default added-addon" value="1"><div class="item-added-container"><div class="item-inner"><div class="text"><p>Hello to you</p><p>this is</p><p>it you know</p><p>s</p></div></div><div class="editlist" style="visibility: hidden;"><ul class="list-inline editbtns2"><li><button class="movetop"><span class="glyphicon glyphicon-arrow-up"></span> Move To Top</button></li><li><button class="moveup"><span class="glyphicon glyphicon-chevron-up"></span> Move Up</button></li><li><button class="editItem" onclick="edit_addon('1', 'text', 'addon', 'edit', 'edit')"><span class="glyphicon glyphicon-edit"></span> Edit</button></li><li><button class="deleteItem" onclick="delete_item('1', 'text', 'new')"><span class="glyphicon glyphicon-remove-sign"></span> Delete</button></li><li class="right sort"><span class="sort-item ui-sortable-handle"><span class="glyphicon glyphicon-move"></span> Sort this item</span></li></ul></div></div><div class="add-item-area"><div class="append-new-item"></div><div class="add-inner" style="display: none;"><div class="show-append-here"></div><div class="item-btn-con"><div class="item-hr"><hr></div><div class="add-item-btn right"><a href="javascript:void(0)" onclick="show_appended_item_area(1)">Add New Addon</a></div></div></div></div><input type="hidden" class="type" value="text"></li>
						
						
						
						
						
						
						
																																																																																																																																			